### ISSUE TITLE
Same package is being created for different architecture settings.

### ISSUE THREAD

**Issue by suriya1611** [theodelrieu/conan-android-ndk#1]
When i tried to run the build.py file, only one package is being created. But there are two different architectures being passed in the build.py file with different options( armv7 and armv8).
If i am not wrong about conan, shouldn't a change in the settings or profile result in a different package?
Correct me if i am wrong about this or misunderstood anything. 
Thank you.

**Comment by theodelrieu** [comment]
Hello,

This package is meant to be used as a build requirement, it contains the whole NDK and should therefore be only created once. The only settings that are taken into account when calculating the package ID are `os_build` and `arch_build` (see the conanfile's `package_id` method). This is to avoid downloading Windows binaries on a Linux machine for example.

All other settings/options are used in the conanfile's `package` method to expose different flags, and thus you do not need to have multiple copies of the same package (which is really huge, 500MB compressed)

**Comment by suriya1611** [comment]
yeah just saw that, thank you for the swift reply :) nice work btw. I'm new to conan, your work has been very helpful :)

**Comment by theodelrieu** [comment]
No problem, thanks a lot!
