### ISSUE TITLE
conan-boost not compiling

### ISSUE THREAD

**Issue by Linux13524** [theodelrieu/conan-android-ndk#4]
### Package and Environment Details 
  * Package Name/Version: **boost/1.66.0** and **boost/1.68.0**
  * Operating System+version: **Fedora 29**
  * Compiler+version: **clang 7.0** (Android NDK)
  * Conan version: **conan 1.11.2**
  * Python version: **Python 3.7.2**

### Conan profile
```
[settings]
os=Android
arch=armv7
os.api_level=21
compiler=clang
compiler.libcxx=libc++
compiler.version=7.0
build_type=Release
os_build=Linux
arch_build=x86_64

[build_requires]
android-ndk/r18@theodelrieu/testing
```
### Steps to reproduce
```
conan remote add theodelrieu https://api.bintray.com/conan/theodelrieu/conan-repo
git clone https://github.com/conan-community/conan-boost.git -b release/1.66.0
cd conan-boost
conan create . linux13524/testing -pr android -b missing
```
### Description

When I try to compile boost I get different errors for different versions. 
First I tried to compile version 1.66.0 since its the version Im currently using. This gives some errors like:
```
libs/context/src/asm/ontop_arm_aapcs_elf_gas.S:46:5: error: unexpected token at start of statement
    @ save LR as PC
    ^
libs/context/src/asm/ontop_arm_aapcs_elf_gas.S:47:11: error: unknown token in expression
    push {lr}
          ^
libs/context/src/asm/ontop_arm_aapcs_elf_gas.S:48:5: error: unexpected token at start of statement
    @ save hidden,V1-V8,LR
    ^
libs/context/src/asm/ontop_arm_aapcs_elf_gas.S:49:11: error: unknown token in expression
    push {a1,v1-v8,lr}
          ^
```
Maybe this is related to conan-community/community#139 ?

Then I tried to compile version 1.68.0 giving following error not finding `clang`:    

```
### Using 'clang' toolset.
###
rm -rf bootstrap
mkdir bootstrap
clang -Wno-unused -Wno-format -o bootstrap/jam0 command.c compile.c constants.c debug.c execcmd.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c class.c cwd.c native.c md5.c w32_getreg.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c execunix.c fileunix.c pathunix.c
./build.sh: line 17: clang: command not found
```

Any ideas? Let me know if you need more infos / logs.

**Comment by theodelrieu** [comment]
Hello, this is exactly the issue you linked.

For the second part I will push a fix (I forgot to add the `bin` folder to `PATH`...)

**Comment by Linux13524** [comment]
Ok, now I get the same error for 1.66.0 and 1.68.0. 
Since there is already an open issue for it I will close this one.

**Comment by theodelrieu** [comment]
I realized that adding the NDK's `bin` folder to `PATH` was wrong...

The reason why you had that error is because the boost recipe looks at `self.settings.compiler` to know which toolset to use. Unfortunately, we are cross-building and the `settings.compiler` cannot be used to compile build tools...

The patch I've made results in boost_build being built for Android...

I'll try to find a solution and revert the patch once I do
