### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by paulocoutinhox** [theodelrieu/conan-android-ndk#5]
Hi,

First: How i can use this repository on my build?

Im trying compile with it but get error:

```
android-ndk/r18@theodelrieu/testing: Trying with 'conan-center'...
ERROR: Unable to find 'android-ndk/r18@theodelrieu/testing' in remotes
```

My profile:

```
include(default)

[settings]
os=Android
os.api_level=21
compiler=clang
compiler.version=7.0
arch=armv7

[build_requires]
android-ndk/r18@theodelrieu/testing
```

Second question is: How i can fork it and use my fork on profile?

**Comment by paulocoutinhox** [comment]
Can you help me please?

I need compile my package to Android on my open-source project to mobile.

Im using your iOS toolchain and is working fine, but i my new to conan and im converting my project to use conan (ezored.com).

Help me use this to Android.

Thanks.

**Comment by theodelrieu** [comment]
I've updated the Readme to answer your questions, can I close the issue?

**Comment by paulocoutinhox** [comment]
Sure. Thanks.
