### ISSUE TITLE
What are the differences between your repo and bincrafters/conan-android_ndk_installer?

### ISSUE THREAD

**Issue by Hopobcn** [theodelrieu/conan-android-ndk#9]
Hi, I'm a bit confused regarding which build_requirement to use, yours or  https://github.com/bincrafters/conan-android_ndk_installer 

I've seen that you are a contributor in the bincrafters repository, Maybe you know the differences (if any).

Thanks!

**Comment by theodelrieu** [comment]
Hello,

Bincrafters' repo is an enhancement of this one, I should point it out in the readme.

Thanks for the reminder!
